#-----------------------------------------------------------------------
#
# Snort- Configuration File
#
#-----------------------------------------------------------------------
#
# tag: tag asociated with the files
#
# structured: Boolean ver to indicate if datasource is structured or not.
#
# timestamp_format: format of the timestamp of the logs in the files of 
#                   this dataSource in python datetime format, see https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
#
# timestamp_regexp: regular expresion that matches the date format of the source (only needed for unstructured sources)
#
# separator: chars that delimitates the log entries of the source (only needed in unstructured sources)
#
# timearg: position of the timestamp in the log entry (only needed in structured sources)
#
# VARIABLES:
#   - name:      Variable name.
#     matchtype:      Variable matchtype {string, number, counter, ip, time, duration}.
#     where:       Position of the field in the line (starts with 0).
#
#   - ...
#
# FEATURES:
#   - name:      Feature name.
#     variable:  Feature from which the feature is calculated.
#     matchtype:      Feature matchtype {single, multiple, range, default}
#     value:     Value of the field that defines the feature.
#                If the matchtype is 'single' use a single value.
#                If the matchtype is 'multiple', use a list of values.
#                If the matchtype is 'range', use a list of two values.
#                If the matchtype is 'default', the value must be empty.
#   - ...
#-----------------------------------------------------------------------

tag: ids

structured: False

timestamp_format: '%m/%d-%H:%M:%S'

timestamp_regexp: '[0-9]{1,2}/[0-9]{1,2}-([0-9]{1,2}:){2}[0-9]{2}'

separator: "\n\n"

# timearg: 


## variables Section
VARIABLES:

- name: timestamp
  matchtype: string 
  where: '(?P<match>[0-9]{1,2}/[0-9]{1,2}-([0-9]{1,2}:){2}[0-9]{2})'

- name: priority
  matchtype: number 
  where: '(?<=Priority: )(?P<match>[0-9]+)'

- name: label
  matchtype: string
  where: '(?<=\[\*\*\] )(?P<match>(.)+ )'

- name: classification
  matchtype: string
  where: '(?<=\[Classification: )(?P<match>(.)+)(?=\] \[)' 

- name: src_ip
  matchtype: ip
  where: '(?P<match>([0-9]{1,3}\.){3}[0-9]{1,3})(?=:[0-9])'

- name: src_port
  matchtype: number
  where: '(?<=[0-9]:)(?P<match>[0-9]+)(?= \->)'

- name: dst_ip
  matchtype: ip
  where: '(?<= \-> )(?P<match>([0-9]{1,3}\.){3}[0-9]{1,3})(?=:[0-9])'

- name: dst_port
  matchtype: number
  where: '(?P<match>(?<=[0-9]:)[0-9]+)(?=\r)'

- name: proto
  matchtype: string 
  where: '(?P<match>[a-z|A-Z]+)(?= TTL)'

- name: ttl
  matchtype: number
  where: '(?<=TTL:)(?P<match>(.*?))(?= TOS)'

- name: tos
  matchtype: number
  where: '(?<=TOS:0x)(?P<match>(.*?))(?= ID)'
  
- name: ip_len  # ip header length
  matchtype: number
  where: '(?<=IpLen:)(?P<match>(.*?))(?= DgmLen)'

- name: len  # datagram length
  matchtype: number
  where: '(?<=DgmLen:)(?P<match>(.*?))(?= )'

- name: tcp_len  # tcp header length
  matchtype: number
  where: '(?<=TcpLen: )(?P<match>[0-9]+)'

- name: flags  # tcp header length
  matchtype: string
  where: '(?P<match>(.*?))(?= Seq)'

- name: fragments  # tcp header length
  matchtype: string
  where: '(?P<match>DF|CE|MF)'

   

## Variables Section
FEATURES:

- name: ids_prio1
  variable: priority
  matchtype: single
  value: 1
  weight: 

- name: ids_prio2
  variable: priority
  matchtype: single
  value: 2
  weight: 

- name: ids_prio3
  variable: priority
  matchtype: single
  value: 3
  weight: 

- name: ids_prio4
  variable: priority
  matchtype: single
  value: 4
  weight: 

- name: ids_attempted-admin
  variable: classification
  matchtype: regexp
  value: 'Attempted Administrator Privilege Gain'
  weight: 

- name: ids_attempted-user
  variable: classification
  matchtype: regexp
  value: 'Attempted User Privilege Gain'
  weight: 

- name: ids_inappropriate-content
  variable: classification
  matchtype: regexp
  value: 'Inappropriate Content was Detected'
  weight: 

- name: ids_policy-violation
  variable: classification
  matchtype: regexp
  value: 'Potential Corporate Privacy Violation'
  weight: 

- name: ids_shellcode-detect
  variable: classification
  matchtype: regexp
  value: 'Executable code was detected'
  weight: 

- name: ids_successful-admin
  variable: classification
  matchtype: regexp
  value: 'Successful Administrator Privilege Gain'
  weight: 

- name: ids_successful-user
  variable: classification
  matchtype: regexp
  value: 'Successful User Privilege Gain'
  weight: 

- name: ids_trojan-activity
  variable: classification
  matchtype: regexp
  value: '  A Network Trojan was detected'
  weight: 

- name: ids_unsuccessful-user
  variable: classification
  matchtype: regexp
  value: 'Unsuccessful User Privilege Gain'
  weight: 

- name: ids_web-application-attack
  variable: classification
  matchtype: regexp
  value: 'Web Application Attack'
  weight: 

- name: ids_attempted-dos
  variable: classification
  matchtype: regexp
  value: 'Attempted Denial of Service'
  weight: 

- name: ids_attempted-recon
  variable: classification
  matchtype: regexp
  value: 'Attempted Information Leak'
  weight: 

- name: ids_bad-unknown
  variable: classification
  matchtype: regexp
  value: 'Potentially Bad Traffic'
  weight: 

- name: default-login-attempt
  variable: classification
  matchtype: regexp
  value: 'Attempt to login by a default username and password'
  weight: 

- name: ids_denial-of-service
  variable: classification
  matchtype: regexp
  value: 'Detection of a Denial of Service Attack'
  weight: 

- name: ids_misc-attack
  variable: classification
  matchtype: regexp
  value: 'Misc Attack'
  weight: 

- name: ids_non-standard-protocol
  variable: classification
  matchtype: regexp
  value: 'Detection of a non-standard protocol or event'
  weight: 

- name: ids_rpc-portmap-decode
  variable: classification
  matchtype: regexp
  value: 'Decode of an RPC Query'
  weight: 

- name: successful-dos
  variable: classification
  matchtype: regexp
  value: 'Denial of Service'
  weight: 

- name: ids_successful-recon-largescale
  variable: classification
  matchtype: regexp
  value: 'Large Scale Information Leak'
  weight: 

- name: ids_successful-recon-limited
  variable: classification
  matchtype: regexp
  value: 'Information Leak'
  weight: 

- name: ids_suspicious-filename-detect
  variable: classification
  matchtype: regexp
  value: 'A suspicious filename was detected'
  weight: 

- name: ids_suspicious-login
  variable: classification
  matchtype: regexp
  value: 'An attempted login using a suspicious username was detected'
  weight: 

- name: system-call-detect
  variable: classification
  matchtype: regexp
  value: 'A system call was detected'
  weight: 

- name: ids_unusual-client-port-connection
  variable: classification
  matchtype: regexp
  value: 'A client was using an unusual port'
  weight: 

- name: ids_web-application-activity
  variable: classification
  matchtype: regexp
  value: 'Access to a potentially vulnerable web application'
  weight: 

- name: ids_icmp-event
  variable: classification
  matchtype: regexp
  value: 'Generic ICMP event'
  weight: 

- name: ids_misc-activity
  variable: classification
  matchtype: regexp
  value: 'Misc activity'
  weight: 

- name: ids_network-scan
  variable: classification
  matchtype: regexp
  value: 'Detection of a Network Scan'
  weight: 

- name: ids_not-suspicious
  variable: classification
  matchtype: regexp
  value: 'Not Suspicious Traffic'
  weight: 

- name: ids_protocol-command-decode
  variable: classification
  matchtype: regexp
  value: 'Generic Protocol Command Decode'
  weight: 

- name: ids_string-detect
  variable: classification
  matchtype: regexp
  value: 'A suspicious string was detected'
  weight: 

- name: ids_unknown
  variable: classification
  matchtype: regexp
  value: 'Unknown Traffic'
  weight: 

- name: ids_tcp-connection
  variable: classification
  matchtype: regexp
  value: '  A TCP connection was detected'
  weight: 


- name: ids_snmp_req
  variable: label
  matchtype: regexp
  value: 'GPL SNMP request tcp'
  weight: 

- name: ids_irc_auth
  variable: label
  matchtype: regexp
  value: 'ET POLICY IRC authorization message'
  weight: 

- name: ids_ssh_scan1
  variable: label
  matchtype: regexp
  value: 'ET SCAN Potential SSH Scan'
  weight: 

- name: ids_ssh_scan2
  variable: label
  matchtype: regexp
  value: 'ET SCAN Behavioral Unusually fast Terminal Server Traffic, Potential Scan or Infection'
  weight: 

- name: ids_ssh_scan_outbound
  variable: label
  matchtype: regexp
  value: 'ET SCAN Potential SSH Scan OUTBOUND'
  weight: 

- name: ids_vnc_scan
  variable: label
  matchtype: regexp
  value: 'ET SCAN Potential VNC Scan'
  weight:

- name: ids_brute_force
  variable: label
  matchtype: regexp
  value: 'Possible Brute Force Attack'
  weight:

- name: ids_dns_update
  variable: label
  matchtype: regexp
  value: 'ET POLICY DNS Update From External net'
  weight:

- name: ids_inbound_*SQL
  variable: label
  matchtype: regexp
  value: 'ET POLICY Suspicious inbound to (.)+SQL'
  weight: 

- name: ids_behav_scan
  variable: label
  matchtype: regexp
  value: 'ET SCAN Behavioral Unusually fast Terminal Server Traffic'
  weight: 

- name: ids_netbios
  variable: label
  matchtype: regexp
  value: 'GPL NETBIOS SMB'
  weight: 


# source port
- name: ids_sport_zero
  variable: src_port
  matchtype: single
  value: 0
- name: ids_sport_multiplex
  variable: src_port
  matchtype: single
  value: 1
- name: ids_sport_echo
  variable: src_port
  matchtype: single
  value: 7
- name: ids_sport_discard
  variable: src_port
  matchtype: single
  value: 9
- name: ids_sport_daytime
  variable: src_port
  matchtype: single
  value: 13
- name: ids_sport_quote
  variable: src_port
  matchtype: single
  value: 17
- name: ids_sport_chargen
  variable: src_port
  matchtype: single
  value: 19
- name: ids_sport_ftp_data
  variable: src_port
  matchtype: single
  value: 20
- name: ids_sport_ftp_control
  variable: src_port
  matchtype: single
  value: 21
- name: ids_sport_ssh
  variable: src_port
  matchtype: single
  value: 22
- name: ids_sport_telnet
  variable: src_port
  matchtype: single
  value: 23
- name: ids_sport_smtp
  variable: src_port
  matchtype: single
  value: 25
- name: ids_sport_dns
  variable: src_port
  matchtype: single
  value: 53
- name: ids_sport_bootp
  variable: src_port
  matchtype: multiple
  value:
  - 67
  - 68
- name: ids_sport_gopher
  variable: src_port
  matchtype: single
  value: 70
- name: ids_sport_finger
  variable: src_port
  matchtype: single
  value: 79
- name: ids_sport_http
  variable: src_port
  matchtype: single
  value: 80
- name: ids_sport_kerberos
  variable: src_port
  matchtype: single
  value: 88
- name: ids_sport_pop3
  variable: src_port
  matchtype: single
  value: 110
- name: ids_sport_nntp
  variable: src_port
  matchtype: single
  value: 119
- name: ids_sport_ntp
  variable: src_port
  matchtype: single
  value: 123
- name: ids_sport_netbios
  variable: src_port
  matchtype: multiple
  value:
  - 137
  - 138
  - 139
- name: ids_sport_imap4
  variable: src_port
  matchtype: single
  value: 143
- name: ids_sport_snmp
  variable: src_port
  matchtype: single
  value: 161
- name: ids_sport_ldap
  variable: src_port
  matchtype: single
  value: 389
- name: ids_sport_https
  variable: src_port
  matchtype: single
  value: 443
- name: ids_sport_mds
  variable: src_port
  matchtype: single
  value: 445
- name: ids_sport_kpasswd
  variable: src_port
  matchtype: single
  value: 464
- name: ids_sport_smtp_ssl
  variable: src_port
  matchtype: single
  value: 465
- name: ids_sport_syslog
  variable: src_port
  matchtype: single
  value: 514
- name: ids_sport_smtp
  variable: src_port
  matchtype: single
  value: 587
- name: ids_sport_ldaps
  variable: src_port
  matchtype: single
  value: 636
- name: ids_sport_cups
  variable: src_port
  matchtype: single
  value: 631
- name: ids_sport_imap4
  variable: src_port
  matchtype: single
  value: 993
- name: ids_sport_socks
  variable: src_port
  matchtype: single
  value: 1080
- name: ids_sport_openvpn
  variable: src_port
  matchtype: single
  value: 1194
- name: ids_sport_mssql
  variable: src_port
  matchtype: multiple
  value:
  - 1433
  - 1434
- name: ids_sport_citrix
  variable: src_port
  matchtype: single
  value: 1494
- name: ids_sport_oracle
  variable: src_port
  matchtype: single
  value: 1521
- name: ids_sport_rapservice
  variable: src_port
  matchtype: single
  value: 1530
- name: ids_sport_msnmessenger
  variable: src_port
  matchtype: single
  value: 1863
- name: ids_sport_mgc
  variable: src_port
  matchtype: single
  value: 3268
- name: ids_sport_mysql
  variable: src_port
  matchtype: single
  value: 3306
- name: ids_sport_metasploit
  variable: src_port
  matchtype: single
  value: 4444
- name: ids_sport_emule
  variable: src_port
  matchtype: single
  value: 4662
- name: ids_sport_xmpp
  variable: src_port
  matchtype: single
  value: 5222
- name: ids_sport_bittorrent
  variable: src_port
  matchtype: single
  value: 6881
- name: ids_sport_http2
  variable: src_port
  matchtype: single
  value: 8080
- name: ids_sport_reserved
  variable: src_port
  matchtype: range
  value:
  - 0
  - 1023
- name: ids_sport_register
  variable: src_port
  matchtype: range
  value:
  - 1024
  - 49151
- name: ids_sport_private
  variable: src_port
  matchtype: range
  value:
  - 49152
  - 65535


# destination port
- name: ids_dport_zero
  variable: dst_port
  matchtype: single
  value: 0
- name: ids_dport_multiplex
  variable: dst_port
  matchtype: single
  value: 1
- name: ids_dport_echo
  variable: dst_port
  matchtype: single
  value: 7
- name: ids_dport_discard
  variable: dst_port
  matchtype: single
  value: 9
- name: ids_dport_daytime
  variable: dst_port
  matchtype: single
  value: 13
- name: ids_dport_quote
  variable: dst_port
  matchtype: single
  value: 17
- name: ids_dport_chargen
  variable: dst_port
  matchtype: single
  value: 19
- name: ids_dport_ftp_data
  variable: dst_port
  matchtype: single
  value: 20
- name: ids_dport_ftp_control
  variable: dst_port
  matchtype: single
  value: 21
- name: ids_dport_ssh
  variable: dst_port
  matchtype: single
  value: 22
- name: ids_dport_telnet
  variable: dst_port
  matchtype: single
  value: 23
- name: ids_dport_smtp
  variable: dst_port
  matchtype: single
  value: 25
- name: ids_dport_dns
  variable: dst_port
  matchtype: single
  value: 53
- name: ids_dport_bootp
  variable: dst_port
  matchtype: multiple
  value:
  - 67
  - 68
- name: ids_dport_gopher
  variable: dst_port
  matchtype: single
  value: 70
- name: ids_dport_finger
  variable: dst_port
  matchtype: single
  value: 79
- name: ids_dport_http
  variable: dst_port
  matchtype: single
  value: 80
- name: ids_dport_kerberos
  variable: dst_port
  matchtype: single
  value: 88
- name: ids_dport_pop3
  variable: dst_port
  matchtype: single
  value: 110
- name: ids_dport_nntp
  variable: dst_port
  matchtype: single
  value: 119
- name: ids_dport_ntp
  variable: dst_port
  matchtype: single
  value: 123
- name: ids_dport_netbios
  variable: dst_port
  matchtype: multiple
  value:
  - 137
  - 138
  - 139
- name: ids_dport_imap4
  variable: dst_port
  matchtype: single
  value: 143
- name: ids_dport_snmp
  variable: dst_port
  matchtype: single
  value: 161
- name: ids_dport_ldap
  variable: dst_port
  matchtype: single
  value: 389
- name: ids_dport_https
  variable: dst_port
  matchtype: single
  value: 443
- name: ids_dport_mds
  variable: dst_port
  matchtype: single
  value: 445
- name: ids_dport_kpasswd
  variable: dst_port
  matchtype: single
  value: 464
- name: ids_dport_smtp_ssl
  variable: dst_port
  matchtype: single
  value: 465
- name: ids_dport_syslog
  variable: dst_port
  matchtype: single
  value: 514
- name: ids_dport_smtp
  variable: dst_port
  matchtype: single
  value: 587
- name: ids_dport_ldaps
  variable: dst_port
  matchtype: single
  value: 636
- name: ids_dport_cups
  variable: dst_port
  matchtype: single
  value: 631
- name: ids_dport_imap4
  variable: dst_port
  matchtype: single
  value: 993
- name: ids_dport_socks
  variable: dst_port
  matchtype: single
  value: 1080
- name: ids_dport_openvpn
  variable: dst_port
  matchtype: single
  value: 1194
- name: ids_dport_mssql
  variable: dst_port
  matchtype: multiple
  value:
  - 1433
  - 1434
- name: ids_dport_citrix
  variable: dst_port
  matchtype: single
  value: 1494
- name: ids_dport_oracle
  variable: dst_port
  matchtype: single
  value: 1521
- name: ids_dport_rapservice
  variable: dst_port
  matchtype: single
  value: 1530
- name: ids_dport_msnmessenger
  variable: dst_port
  matchtype: single
  value: 1863
- name: ids_dport_mgc
  variable: dst_port
  matchtype: single
  value: 3268
- name: ids_dport_mysql
  variable: dst_port
  matchtype: single
  value: 3306
- name: ids_dport_metasploit
  variable: dst_port
  matchtype: single
  value: 4444
- name: ids_dport_emule
  variable: dst_port
  matchtype: single
  value: 4662
- name: ids_dport_xmpp
  variable: dst_port
  matchtype: single
  value: 5222
- name: ids_dport_bittorrent
  variable: dst_port
  matchtype: single
  value: 6881
- name: ids_dport_http2
  variable: dst_port
  matchtype: single
  value: 8080
- name: ids_dport_reserved
  variable: dst_port
  matchtype: range
  value:
  - 0
  - 1023
- name: ids_dport_register
  variable: dst_port
  matchtype: range
  value:
  - 1024
  - 49151
- name: ids_dport_private
  variable: dst_port
  matchtype: range
  value:
  - 49152
  - 65535

# source IP
- name: ids_src_ip_private
  variable: src_ip
  matchtype: single
  value: private
- name: ids_src_ip_public
  variable: src_ip
  matchtype: single
  value: public
- name: ids_src_ip_default
  variable: src_ip
  matchtype: default
  value: 

# destination IP
- name: ids_dst_ip_private
  variable: dst_ip
  matchtype: single
  value: private
- name: ids_dst_ip_public
  variable: dst_ip
  matchtype: single
  value: public
- name: ids_dst_ip_default
  variable: dst_ip
  matchtype: default
  value: 












